name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-verson:
          - "3.9"
          - "3.13"
        include:
          - python-version: pypy-3.9
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: uv sync --all-extras

      - name: Run tests for ${{ matrix.python-version }} on ${{ matrix.os }}
        run: uv run pytest --durations=10

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

  typesafety:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install
        run: uv sync --all-extras

      - name: Typecheck project
        run: uv run pyright
      - name: Ensure typing coverage
        run: uv run pyright --ignoreexternal --verifytypes=aocd
